### ISSUE TITLE
vcpkg install boost:x64-windows

### ISSUE THREAD

**Issue by violet17** [BabaGodPikin/Build-OpenCv-for-Python-with-Extra-Modules-Windows-10#1]
@BabaGodPikin 
Hi, 
Thank you very much for the step-by-step guide. It is so great!
I have finally installed freetype in my win10.

And I think it might be some typo in vcpkg installation, like `vcpkg install boost:x64-windows `
Do you mean `vcpkg install freetype:x64-windows`?

Thanks again.

**Comment by BabaGodPikin** [comment]
@violet17 

Glad you found it useful. You are right @typo. I corrected it.
