### ISSUE TITLE
Created a YouTube video for the whole process...

### ISSUE THREAD

**Issue by saumya-banthia** [BabaGodPikin/Build-OpenCv-for-Python-with-Extra-Modules-Windows-10#2]
Hey Dude,

Thanks a lot for creating this comprehensive guide.

I went ahead and created a video for the whole process, and I've credited you for it in the video.

Here's the video link: https://youtu.be/9YUDx3qzKwY

If you're willing to, you can include this in your post too.

Once again, Thanks a lot for your help on this one!

(_Also sorry about letting you know by posting an issue, but I could not find a contact info on your GitHub profile_)

Cheers!

**Comment by BabaGodPikin** [comment]
> Hey Dude,
> 
> Thanks a lot for creating this comprehensive guide.
> 
> I went ahead and created a video for the whole process, and I've credited you for it in the video.
> 
> Here's the video link: https://youtu.be/9YUDx3qzKwY
> 
> If you're willing to, you can include this in your post too.
> 
> Once again, Thanks a lot for your help on this one!
> 
> (_Also sorry about letting you know by posting an issue, but I could not find a contact info on your GitHub profile_)
> 
> Cheers!

@saumya-banthia  Sure no Problem. I went ahead to edit my profile to include contact info. I appreciate that you quoted my Github project.
